### ISSUE TITLE
Reset counters for each req on SSR

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#101]
JSS core api has been changed to accept `createGenerateClassName` during setup and now we need to pass generateClassName fn as an option to createStyleSheet. We need to create a new HOC which will do what SheetsRegistry does + will use createGenerateClassName from jss and make sure we always pass the a fresh generateClassName to createStyleSheet for each request.

**Comment by kof** [comment]
Its implemented on the next branch now. cc @iamstarkov @jcheroske

**Comment by kof** [comment]
@jcheroske give it a try

**Comment by jcheroske** [comment]
Is the next branch published to npm? If I need to clone @next, then what should I do after that to get my project to use that cloned copy? This is an issue I've struggled with before. I've never seen a good answer, but I assume there is one.

**Comment by kof** [comment]
I can publish a pre release for you.

**Comment by iamstarkov** [comment]
@kof publish it as `@kof/react-jss-issue-101`

**Comment by kof** [comment]
Released 7.0.0-pre, try it out.

**Comment by kof** [comment]
Please reopen the issue if not fixed.

**Comment by jcheroske** [comment]
Ok, I've been testing it, and I'm seeing something odd. My environment is complex, so it might not have anything to do with JSS, but I wanted to run it by you nonetheless. First, I just wanted to say that the old react-jss code and the new code both worked perfectly when deployed to Heroku as a production build. I only ever saw the counter bug during development, as the bug is/was really an interaction between JSS's counter and next.js' dev module reloading. In a prod env, the bug disappears because all of the next.js pages are compiled upon build and only then. That said, I am seeing something new during dev that might be of interest.

The new code is correctly reseting the counter with each request, so WOOT! on that. But, what I see now is still a difference between the server and the client versions of the page.  In a nutshell:

On the server, the first two JSS-generated styles both have the number 0, but on the client numbering goes correctly.

Server:
```
.globalLayout-0-0 {
  font-family: Roboto !important;
}
.formControls-0-0 {
  padding-left: 5px !important;
  padding-right: 5px !important;
}
.formControls-0-0:hover {
  background-color: #f5f5f5 !important;
}
.container-0-1 {
  display: flex !important;
  position: relative !important;
  margin-top: 10px !important;
  padding-top: 5px !important;
  margin-bottom: 10px !important;
  flex-direction: column !important;
  padding-bottom: 5px !important;
}
```
Client:
```
.globalLayout-0-0 {
  font-family: Roboto !important;
}

.formControls-0-1 {
  padding-left: 5px !important;
  padding-right: 5px !important;
}
.formControls-0-1:hover {
  background-color: #f5f5f5 !important;
}
.container-0-2 {
  display: flex !important;
  position: relative !important;
  margin-top: 10px !important;
  padding-top: 5px !important;
  margin-bottom: 10px !important;
  flex-direction: column !important;
  padding-bottom: 5px !important;
}
```
The `JssProvider` is only used on the server. There is definitely a non-zero chance this could be caused by something in `next.js`, but I wanted to run it by you anyway.

**Comment by kof** [comment]
Thats strange, I think the best way to tackle this is to create a "simple" example which we can later add to the examples repository of next.js and at the same time use it for debugging now.

**Comment by jcheroske** [comment]
I agree. I will try and do that when I get a little time. Since SSR works in production, I can tolerate a warning in dev for now.

I do have one idea about the cause, but I need some debug output and don't have next.js running in a debugger. Can you think of an easy way to print out whether or not a given call to `injectSheet` found a `JssProvider` instance? My hunch is that the first call to `injectSheet` happened without a provider in scope.

**Comment by kof** [comment]
injectSheet is not looking for JssProvider instance, it is looking into those 3 things https://github.com/cssinjs/react-jss/blob/next/src/JssProvider.js#L29.

**Comment by kof** [comment]
This is the place you want to put some logs in https://github.com/cssinjs/react-jss/blob/next/src/createHoc.js#L44 and see what you have from the context there.

**Comment by kof** [comment]
Once you nailed it down the best thing to help is to provide a failing test.

**Comment by jcheroske** [comment]
I think it's on my end. The call to create the global layout style is in a strange place compared to the rest of the app. Something about that call is using a different counter and breaking SSR. When I comment it out everything works and I get a clean dev render. Let's call this fixed.

**Comment by kof** [comment]
Oh so you are using jss directly additionally to react-jss? That would explain it, you are using a different class name generator, so they are def. capable of conflicts. Thats an interesting case though we need to take care of either by fixing or by documenting. Once we had only one single source of counters that was impossible.

**Comment by jcheroske** [comment]
No, I'm doing everything via `react-jss`, but that first call is in an HOC stack that's big and complex and is essentially the initialization and provider infrastructure for the whole app. I don't see the bug yet, but it doesn't surprise me that it's there. Working with next.js on the server-side is quite the dark art. Makes me pine for Meteor sometimes.

**Comment by kof** [comment]
Haven't worked with next.js yet, but every one screams like its very good. There should be a proper way to debug it there.

**Comment by jcheroske** [comment]
It's really amazing, so don't think I'm bashing it. I do think the abstractions for working on the server-side are a bit raw and will settle down over time. It's very new and development on it is rapid. Compared to Meteor, it's very lightweight and deploys really nicely. No special infrastructure is needed when deploying, which is a huge improvement I think.

**Comment by kof** [comment]
And yet that case with using jss additionally is real.
One possibility to fix this is to add something to the class name which indicates the instance of Jss in use. Right now we have 2 counters, one indicates the jss library in case someone is using multiple jss versions at the same time, second is rules counter. I could tweak the first one to increase for each Jss instance.

**Comment by jcheroske** [comment]
That would make sense. I really like the counters vs the hash approach, although I can't really say why. Knowing that react renders in a deterministic order is a key bit of knowledge for the counters to work. As long as adding in an instance counter does not break that reproducibility, it sounds like a good idea.

**Comment by kof** [comment]
We still need to verify how your current situation is created and if it is potentially a bug in react-jss somewhere. Can you break it down to something simple?

**Comment by jcheroske** [comment]
Just got back from a bike ride, and I've got some ideas about what might be
going on. I'll try some things and see what I learn.

**Comment by jcheroske** [comment]
Is the new theme stuff available in 7.0.0-pre? I think all of my problems are coming from the `injectSheet` decorator I wrote. I hacked some theming support together, so I could move on with my project while the new `JSS` theming api was finished. I'm eager to port to the new API though, because I think that what I wrote is fundamentally incompatible with SSR.

**Comment by kof** [comment]
Yes, but you have to use withTheme function, see the docs on the next branch.

**Comment by jcheroske** [comment]
I figured out the correct check that I needed to do in my decorator to get SSR working. My dev and prod environments are now getting clean SSR. I think we can close this. If you're interested, here's the HOC I wrote to add very basic static theming and to remove the `sheets` prop, since I never use that one. Your comments are very welcome.
```
import invariant from 'invariant'
import {isFunction, isPlainObject} from 'lodash'
import PropTypes from 'prop-types'
import {Component} from 'react'
import jssInjectSheet from 'react-jss'
import {compose, createEagerFactory} from 'recompose'
import {omitProps} from 'recompose-extras'

const createEnhancer = styles =>
  compose(
    jssInjectSheet(styles),
    omitProps('sheet')
  )

const injectSheet = (styles) => {
  if (isPlainObject(styles)) {
    return createEnhancer(styles)
  }

  invariant(isFunction(styles), `The style parameter must be either a plain object or a function. Got ${styles}`)

  return BaseComponent => {
    let factory, prevJssSheetsRegistry
    return class InjectThemedSheet extends Component {
      static contextTypes = {
        appTheme: PropTypes.object.isRequired,
        jssSheetsRegistry: PropTypes.object
      }

      constructor (_, {appTheme, jssSheetsRegistry}) {
        super()
        if (!factory || prevJssSheetsRegistry !== jssSheetsRegistry) {
          prevJssSheetsRegistry = jssSheetsRegistry
          const themeStyles = styles(appTheme)
          invariant(isPlainObject(themeStyles), `The style function must return a plain object. Got ${themeStyles}`)
          const EnhancedComponent = createEnhancer(themeStyles)(BaseComponent)
          factory = createEagerFactory(EnhancedComponent)
        }
      }

      render () {
        return factory(this.props)
      }
    }
  }
}

export default injectSheet
```
