### ISSUE TITLE
Stylesheet Custom meta

### ISSUE THREAD

**Issue by dsslimshaddy** [cssinjs/react-jss#126]
Adding names to stylesheet in `data-meta` attribute of <style>  will help .

**Comment by kof** [comment]
Can you please explain what problem you are trying to solve here?

**Comment by iamstarkov** [comment]
@dsslimshaddy please explain your problem in more details. right now we cant start to work on issue because lack of details of it. and it confuses a lot, because we do have custom `meta` attribute, which we use and add Components' names in it.

I'm going to close it. @dsslimshaddy feel free to let us know, if we missed smth, if so, please share your use case and problem you are trying to solve.
