### ISSUE TITLE
injectStylesheet: filter injected props

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/react-jss#130]
This issue is part of a series of feedbacks. [I been upgrading the Material-UI solution](https://github.com/callemall/material-ui/pull/7461).
Unfortunately, I had to fork the package in order to reach my goal.
Now, it's time to reconciliation.

### The issue

For performance and debuggability reason, I think that it would be great to have
a `withTheme` boolean option. I some situations, you need `injectStylesheet()` and `withTheme()` at the same time.

**Comment by kof** [comment]
Our new HOC from v7 has a built-in theming support, so that you don't need to wrap a component with withTheme. It decides wether its with or without theming based on your first argument. If argument is a function, we need theming. https://github.com/cssinjs/react-jss/blob/master/src/createHoc.js#L48

**Comment by oliviertassinari** [comment]
I have seen that it's providing [the theme as a property](https://github.com/cssinjs/react-jss/blob/master/src/createHoc.js#L175). The core of my issue is the following. I don't want the child component to render if he doesn't need the theme. Let's say the theme is updated, why should we have to rerender the child component?

**Comment by oliviertassinari** [comment]
But you are right, we have to rerender the children component no matter what given that the class names can change.

**Comment by oliviertassinari** [comment]
So the only issue for Material-UI, is going to have to destructure the theme property everywhere so that the property doesn't end-up on a native dom element.

**Comment by oliviertassinari** [comment]
Given that use use the theme property in <20 % of the situtation, I would rather opt-in that behavior.

**Comment by kof** [comment]
> I don't want the child component to render if he doesn't need the theme. 

If theme has changed, classes will change as well. So we will have to rerender anyways.

> So the only issue for Material-UI, is that we are going to have to destructure the theme property everywhere so that the property doesn't end-up on a native dom element.

Yeah for a lib like mui, we can't just pick props we know are used, because the lib is very generic and at the same time we can't forward everything we get from the outside. So either we remove what we know is not allowed manually or we use something generic that allows only passing props which are allowed. The first way is probably faster as we know exactly the props. Everything else user passes is users responsibility.

**Comment by kof** [comment]
By a generic filter I mean something like this https://github.com/lttb/is-react-prop

**Comment by kof** [comment]
So I suppose we can close this issue, right?

**Comment by oliviertassinari** [comment]
What I mean is that I don't want to have to destructure `theme` everywhere [like with the `classes`](https://github.com/callemall/material-ui/blob/v1-beta/src/Badge/Badge.js#L47)

It don't think that removing it is the best performant solution available.

**Comment by kof** [comment]
There are also other props like classes and sheet you would have to filter as well. I know what you mean, but what can we do? not passing them at all? make it configurable? is it about performance at all?

**Comment by kof** [comment]
Btw. making an option for props list seems legit: `injectSheet(styles, {inject: ['classes', 'sheet', 'theme']})`

**Comment by oliviertassinari** [comment]
> making an option for props list seems legit:

I like that option! I guess the real motivation for me is not having to go through all the components and remove the `theme` almost everywhere.

**Comment by kof** [comment]
Ok, I am adding `inject` option now.

**Comment by kof** [comment]
Released in v8
