### ISSUE TITLE
Make "props" available from the root styles function

### ISSUE THREAD

**Issue by thgala** [cssinjs/react-jss#145]
Is there a way to make "props" available as an argument for the style function?

```js
const styles = props => ({
  button: {
    background: props.color.red
  }
})

@injectSheet(styles)
...
```

Instead of:

```js
const styles = () => ({
  button: {
    background: props => props.color.red
  }
})

@injectSheet(styles)
...
```

I have a lot of different options how my component suppose to look like depends on "props". It seems to be complex - to write a "condition" function for each property.

**Comment by kof** [comment]
No, because what you receive there is a theme object, this function is there to apply theming.

**Comment by kof** [comment]
Also we can't add it as a second argument because this would cause an overhead on each props change.

**Comment by kof** [comment]
Please create a separate issue if you need help with your use case and explain your actual use case.

**Comment by ilyadoroshin** [comment]
Hi, @kof!
What about the situation when I want to return completely different set of styles for component depending on it's props? like

```javascript
const styles = (theme) => {
  button: ({ primary }) => (
    primary
    ? {
        color: 'blue',
        borderColor: 'darkblue'
      }
    : {
      color: '#ddd',
      borderColor: '#aaa'
    }
  )
}
```

What's the best way to do that?
Thanks!

**Comment by ilyadoroshin** [comment]
@kof or it's better to keep this logic in component? 
like 

```javascript
const Button =

**Comment by kof** [comment]
If one property controls the entire style sheet, you can produce 2 base buttons in advance and decide which one to render in the main button.

If many properties are deciding, you have to decide per rule, either using function rules and function values or by concatenating classes in render.

I am in favor of function rules and values because it keeps style logic with styles and you can have cleaner render.
