### ISSUE TITLE
With media queries, Function rules create unexpected conflicts 

### ISSUE THREAD

**Issue by abradley2** [cssinjs/react-jss#193]
The issue occurs when nesting for media queries but not when nesting for psuedo selectors

https://codesandbox.io/s/21rpyo7lwj

In a nutshell:
```
const styles =  {
  wrapper: {
    color: ({ theme }) => theme.color,
    ['@media (min-width: 600px)']: {
      color: 'blue',
    },
  }
}
```

The above will always be whatever `theme.color` is as opposed to blue.

The workaround to this is to wrap the color in a function itself and do:
```
const styles =  {
  wrapper: {
    color: ({ theme }) => theme.color,
    ['@media (min-width: 600px)']: {
      color: () => 'blue',
    },
  }
}
```

also, the alternative way of writing styles for a media query exhibits the same issue:
```
const styles =  {
  wrapper: {
    color: ({ theme }) => theme.color,
  },
  ['@media (min-width: 600px)']: {
    wrapper: {
      color: 'blue'
    }
  },
}
```
^ will still always show `theme.color`

**Comment by kof** [comment]
yeah, looks like a bug

**Comment by kof** [comment]
Looked again. It is actually a behaviour that we kinda expected, because function value are rendered in a separate style tag, separately from the static rule, it always gets a higher source order specificity.

So far I don't know how to fix that if we want to continue reusing static styles between the elements and only rerender dynamic styles. This is basically a consequence of this optimization.
