### ISSUE TITLE
Expect to provide support for typescript

### ISSUE THREAD

**Issue by niqingyang** [cssinjs/react-jss#194]
Eager to provide support for typescript, especially to provide a typescript declaration file, to know if there is a plan for this

**Comment by kof** [comment]
feel free https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23116

**Comment by pbedat** [comment]
Just in case anybody else is looking for react-jss declarations: Instead of fighting with TypeScripts type system and trying to figure out the declarations yourself - take a look at https://github.com/mui-org/material-ui/blob/v1-beta/src/styles/withStyles.d.ts
Those declarations can be easily adapted for react-jss. I'm still figuring out, wether my implementation might be good enough to bring them to @types/react-jss ;)

**Comment by alexandcote** [comment]
@pbedat do you already have something done ? 😄🙏

**Comment by pbedat** [comment]
@alexandcote nothing official, because I have not been using the theming features yet and didn't have to create declarations for that part...
Here is a Gist with the declarations I got away with ;)
https://gist.github.com/pbedat/26eb9376ac11041e1106cad5f1e7606f
