### ISSUE TITLE
Recommended pattern for overriding styles?

### ISSUE THREAD

**Issue by trusktr** [cssinjs/react-jss#290]
Is there a recommended pattern for overriding component styles? (besides Theming)

F.e., Material-UI has some interesting ways to [override styles](https://material-ui.com/customization/overrides/).

**Comment by trusktr** [comment]
It has an interesting way of generating class names, based on component constructor names.

**Comment by kof** [comment]
All non material-ui specific ways are supported.

**Comment by trusktr** [comment]
@kof Which ways are those? I'm trying to learn. The docs only mention theming, but I'd like to know if there's some pattern you recommend most in order to make components stylable by parent components.

**Comment by kof** [comment]
I recommend to not override any css from the parent, but to pass a prop that tells the child what to do. Besides of this and theming you can also pass a className that child needs to add, but thats the least preferable way, because your class name can overwrite any css property and as a parent you don't know what can break if those are decoupled components.
