### ISSUE TITLE
"withStyle" vs "injectSheet"

### ISSUE THREAD

**Issue by trusktr** [cssinjs/react-jss#292]
I like to write

```js
import withStyle from 'react-jss'

@withStyle(styles)
class Foo extends React.Component {...}
```

with style. 😄 

I thought I'd share it, because it sounds better. Maybe consider using that name in the docs? (the default export can be named anything when imported).

Also, various libraries use "withFoo" to describe a class with a "foo" mixin or behavior. For example, [SkateJS](http://skatejs.netlify.com/) mixins are `withUpdate`, `withChildren`, etc.

The `with` prefix is catching on nowadays for these types of things.

**Comment by kof** [comment]
I like withStyles too ... yes it is styles not style, because of the vocabulary in CSSOM. And yet I don't know if there is much value in renaming it, since it would create wording issues in projects which already use injectSheet and some co-workers might start using both ways.

Liking something is usually not good enough reason to introduce 2 syntaxes for the same thing.

**Comment by kof** [comment]
Btw. injectSomething is also a popular syntax for HOCs.

**Comment by kof** [comment]
useSomething is also a  popular one.
