### ISSUE TITLE
Wrong classes ordering usage

### ISSUE THREAD

**Issue by Tarlord** [cssinjs/react-jss#42]
Hi

I found an issue with jss for multiple classes case, so the problem is :

If i am writing class like this: 
`let class = classnames(jss.firstClass, jss.secondClass)`

and then i have object with styles:

`let styles = {
 secondClass: { color: '#fff' },
 firstClass: { color: '#000' } 
}`

in result i will have color: '#000', as top one in stylesheet(css) and white color(color: '#fff') will be overwritten with firstClass. It does not matter that i wrote secondClass after firstClass in classnames(also class that i have in result is - class="firstClass-${id} secondClass-${id}").

If i am changing positions in object like: 

`let styles = {
 firstClass: { color: '#000' },
 secondClass: { color: '#fff' } 
}`

then it works fine, because secondClass is after firstClass in object iterations.

Can it be done by ordering of classes and not ordering in styles object, because it can cause a lot more issues in future?

**Comment by kof** [comment]
This is because firstClass selector is stronger than the second because it is later in the source order. This is not about jss, but css. I would recommend to not to use multiple classes on one element (mixing the rule instead) to avoid such things or ensure the right order within the style sheet as you suggest.
