### ISSUE TITLE
createStyleSheet not working as expected

### ISSUE THREAD

**Issue by PolGuixe** [cssinjs/react-jss#77]
I am trying to user `jss.createStyleSheet` however I can't manage to make it work. Here is the component: 
```
import React from 'react';
import jss from 'jss';
import injectSheet from 'react-jss';

const sheet = jss.createStyleSheet({
  box: {
    boxSizing: 'border-box',
    position: 'relative',
    minHeight: '1rem',
    marginBottom: 0,
    background: '#007FFF',
    border: '1px solid #FFF',
    borderRadius: '2px',
    overflow: 'hidden',
    textAlign: 'center',
    color: 'white',
  },
});

// const Box = ({ classes }) => (
//   <div className={classes.box} />
// );

class Box extends React.PureComponent {
  render() {
    return (
      <div className={this.props.classes.box} />
    );
  }
}

export default injectSheet(sheet)(Box);
```

Here the style it generates: 
```

.box-1-0 {
  boxSizing: border-box;
  position: relative;
  minHeight: 1rem;
  marginBottom: 0;
  background: #007FFF;
  border: 1px solid #FFF;
  borderRadius: 2px;
  overflow: hidden;
  textAlign: center;
  color: white;
}
```

It doesn't seem to parse to CSS properly.

**Comment by kof** [comment]
Why are u using createStyleSheet together with react-jss, u can pass the
styles object directly to the injectSheet.


Otherwise your problem is that u are using jss instance which wasn't setup
with plugins.

**Comment by PolGuixe** [comment]
As specified here: https://github.com/cssinjs/react-jss#reuse-same-stylesheet-in-different-components 
(well in the example it is using a decorator)

I am using createStyleSheet, because I want to reuse this particular sheet in other components e.g. `BoxRow`, `BoxCol`, etc.

Honestly I don't know how to do it, I was just trying different approaches given the example above.

**Comment by kof** [comment]
Then you need to setup jss instance once before using it http://cssinjs.org/js-api?v=v6.5.0#setup-jss-instance

**Comment by PolGuixe** [comment]
@kof thanks. 

Then `classes.box` would be available in all everytime I am using `injectSheet()`.

**Comment by kof** [comment]
yes 👍

On Mar 21, 2017 00:21, "PolGuixe" <notifications@github.com> wrote:

@kof <https://github.com/kof> thanks.

Then classes.box would be available in all everytime I am using
injectSheet().

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cssinjs/react-jss/issues/77#issuecomment-287916563>,
or mute
the thread

**Comment by PolGuixe** [comment]
There must be something I am doing wrong cause it is not working.

**Comment by kof** [comment]
Can u give me a working example on some playground?

On Mar 21, 2017 15:34, "PolGuixe" <notifications@github.com> wrote:

There must be something I am doing wrong cause it is not working.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cssinjs/react-jss/issues/77#issuecomment-288079351>,
or mute
the thread

**Comment by PolGuixe** [comment]
Would a repo work?

**Comment by kof** [comment]
Anything I can quickly run.

**Comment by PolGuixe** [comment]
@kof I reproduce it the issue in this branch: https://github.com/Zetoff/react-flexbox-grid-jss-demo/tree/debug-jss

To setup the project do: 
` yarn install`

To run the project do: 
`yarn start`

The files are:
- Components: 
  - /components/boxes/Box.jsx  - Here l am trying to set up the stylesheet I want to reuse.
  - /components/boxes/BoxRow.jsx. - Here I am trying to reuse the stylesheet. 

- This components are used here:
  - /src/home/index.js 

Let me know if you have any problems.

**Comment by kof** [comment]
try the latest version, there has been one bug you might have stumbled upon.
