### ISSUE TITLE
Injecting a stylesheet before component sheets

### ISSUE THREAD

**Issue by rudeayelo** [cssinjs/react-jss#85]
We have this small problem at our company, we include a set of functional classes that we then compose inside components (using `jss-composes`). But we're facing this situation where the component styles get overridden by the functional classes because their stylesheets are loaded AFTER the component's.

Is there a way to modify the `index` property for `react-jss` injected sheets?

**Comment by kof** [comment]
How do you render the rules you compose? JSS or its somewhere else?
And yes, you can simply pass the index option `injectSheet(styles, {index})`. Though consider that in react-jss initial index value is [this](https://github.com/cssinjs/react-jss/blob/master/src/index.js#L155) this is done  in order to maintain the specificity for react, where parent component might pass a class to the child and expect it to be with higher specificity.

Please next time give me a small working example that represents the problem. Because it matters.

**Comment by rudeayelo** [comment]
Sorry for not including the code example, next time I'll make sure I include it.

Yes we're attaching the functional classes using JSS like:
```js
jss.createStyleSheet({ '@global': functionalClasses }).attach()
```
so I guess a quick and easy fix would be to execute that with an index even lower than the `react-jss` one, right?
```js
jss.createStyleSheet({ '@global': functionalClasses }, { index: -100001 }).attach()
```

**Comment by kof** [comment]
This is not robust, because we might change the initial index in react-jss, potentially we could export this value so that you don't hardcode it.

Better use the [insertion point](http://cssinjs.org/setup/?v=v7.0.0#specify-dom-insertion-point) feature

**Comment by kof** [comment]
So you can have  multiple insertion points, one is default for all react-jss sheets, one is for you custom global sheets, you need to specify each and add the comment nodes in the correct order

**Comment by rudeayelo** [comment]
Sounds good, thanks @kof

**Comment by kof** [comment]
Btw. feel free to add your company/product to this list http://cssinjs.org/who-is-using

**Comment by rudeayelo** [comment]
Just did it 😉
